Update README.md
Vita3K/Vita3K.github.io pull request #107
Opened 2022-08-30 16:53 UTC by nishinji

RAG also said it should be changed.
I was able to get it to work with jekyll new instead of bundle install.

2022-10-11 13:03 UTC, EXtremeExploit requested changes
just bundle install, sudo is required on linux, dunno about windows

2022-10-12 13:45 UTC, nishinji commented
Corrected
I believe it was only needed the first time

2022-10-12 14:24 UTC, EXtremeExploit commented on .gitignore
> +/.vs
:thinking: why?. also `.vs` is fine, else it becomes a non-relative path

2022-11-02 08:07 UTC, IllusionMan1212 commented
please resolve the conflicts

2022-11-02 08:10 UTC, merged